CREATE TABLE VenteProduits (
    ClefDatePaiement INT,
    ClefHeurePaiement INT,
    ClefCaisse INT,
    ClefMagasin INT,
    ClefPromotion INT,
    ClefProduit INT,
    ClefClient INT,
    ClefModePaiement INT,
    IDPaiement NVARCHAR(50),
    Quantite INT,
    MontantUnitaire DECIMAL(15, 2),
    CoutAchat DECIMAL(15, 2),
    Montant DECIMAL(15, 2),
    Reduction DECIMAL(15, 2),
    MontantFinal DECIMAL(15, 2),
    PRIMARY KEY (ClefDatePaiement, ClefHeurePaiement, ClefCaisse, ClefMagasin, ClefProduit),
    FOREIGN KEY (ClefDatePaiement) REFERENCES Calendrier(ClefDate),
    FOREIGN KEY (ClefHeurePaiement) REFERENCES Temps(ClefTemps),
    FOREIGN KEY (ClefCaisse) REFERENCES Caisse(ClefCaisse),
    FOREIGN KEY (ClefMagasin) REFERENCES Magasin(ClefMagasin),
    FOREIGN KEY (ClefPromotion) REFERENCES Promotion(ClefPromotion),
    FOREIGN KEY (ClefProduit) REFERENCES Produit(ClefProduit),
    FOREIGN KEY (ClefClient) REFERENCES Client(ClefClient),
    FOREIGN KEY (ClefModePaiement) REFERENCES ModePaiement(ClefModePaiement)
);